name: movie_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  lottie: ^1.2.2
  shared_preferences: ^2.0.13
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  get_it: ^7.2.0
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2
  flutter_lints: ^1.0.0
  mockito: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie.json
    - assets/lists.json
    - assets/account_details.json
    - assets/logo.png
